language: haskell

before_install:
  - "export PATH=\"$HOME/.cabal/bin:$PATH\""
  - "cabal update"
  - "cabal install cabal-dev"

script:
  - "make"
  - "cabal clean && cabal-dev install"

notifications:
  irc:
    - "irc.freenode.net#sampla"
