language: haskell

before_install:
  - "sudo apt-get install libpcre3-dev"

install:
  - "cabal update"
  - "cabal install cabal-dev hlint"

script:
  - "hlint src"
  - "make CABAL_FLAGS='-fdevelopment --disable-optimization'"
  - "cabal clean && cabal-dev install"

notifications:
  irc:
    - "irc.freenode.net#sampla"
