language: haskell

before_install:
  - "sudo apt-get install libpcre3-dev"
  - "cabal install cabal-dev"

script:
  - "make"
  - "cabal clean && cabal-dev install"

notifications:
  irc:
    - "irc.freenode.net#sampla"
