language: haskell

before_install:
  - "sudo apt-get install libpcre3-dev"

script:
  - "cabal clean"
  - "cabal install -fdevelopment"
  - "kibr test -a 10000"

notifications:
  irc:
    - "irc.freenode.net#sampla"
